### ISSUE TITLE
Be able to validate a HTTP message in one API call

### ISSUE THREAD

**Issue by Almad** [apiaryio/gavel.js#9]
Like

```
gavel.isValid
    expected:
        request:   request
        response: response
    real:
        request:   request
        response: response
, (err, result) ->
```

would be a welcome wrapper.
